Format action
[skip backend]
[skip frontend]

diff --git a/.github/workflows/FullstackCI.yaml b/.github/workflows/FullstackCI.yaml
--- a/.github/workflows/FullstackCI.yaml
+++ b/.github/workflows/FullstackCI.yaml
@@ -2,9 +2,9 @@ name: Fullstack CI
 
 on:
   push:
-    branches: [ "main" ]
+    branches: ["main"]
   pull_request:
-    branches: [ "main" ]
+    branches: ["main"]
   workflow_dispatch:
 
 jobs:
@@ -35,7 +35,7 @@ jobs:
             frontend:
               - 'Project.App/Project.Client/**'
               - '.github/workflows/FullstackBuild.yaml'
-      
+
       # ...or if there is a commit message override (force/skip)
       # note that force overrides skip
       - name: Check for commit message overrides
@@ -66,7 +66,7 @@ jobs:
 
   backend:
     needs: changes
-    if: | 
+    if: |
       needs.changes.outputs.backend_override == 'force' || (
         needs.changes.outputs.backend_override != 'skip' &&
         needs.changes.outputs.backend == 'true' || needs.changes.result != 'success'
@@ -76,47 +76,47 @@ jobs:
       format_output: ${{ steps.backend_format_check.outputs.output }}
       outcome: ${{ steps.backend_format_check.outcome }}
     steps:
-    - uses: actions/checkout@v4
+      - uses: actions/checkout@v4
 
-    # --- Set up .NET ---
-    - name: Setup .NET
-      uses: actions/setup-dotnet@v4
-      with:
-        dotnet-version: 9.0.x
+      # --- Set up .NET ---
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v4
+        with:
+          dotnet-version: 9.0.x
 
-    # --- Build Backend ---
-    - name: Restore backend dependencies
-      run: dotnet restore ./Project.App/Project.Api/Project.Api.csproj
+      # --- Build Backend ---
+      - name: Restore backend dependencies
+        run: dotnet restore ./Project.App/Project.Api/Project.Api.csproj
 
-    - name: Build backend
-      run: dotnet build ./Project.App/Project.Api/Project.Api.csproj --no-restore
+      - name: Build backend
+        run: dotnet build ./Project.App/Project.Api/Project.Api.csproj --no-restore
 
-    - name: Test backend
-      run: dotnet test ./Project.App/Project.Test/Project.Test.csproj --no-build --verbosity normal
-    
-    - name: Check backend formatting
-      id: backend_format_check
-      run: |
-        dotnet tool restore
+      - name: Test backend
+        run: dotnet test ./Project.App/Project.Test/Project.Test.csproj --no-build --verbosity normal
 
-        set +e # temporarily disable 'exit on error'
-        OUTPUT=$(dotnet csharpier check . 2>&1)
-        EXIT_CODE=$?
-        set -e # re-enable 'exit on error'
+      - name: Check backend formatting
+        id: backend_format_check
+        run: |
+          dotnet tool restore
 
-        echo "output<<EOF" >> $GITHUB_OUTPUT
-        echo "$OUTPUT" >> $GITHUB_OUTPUT
-        echo "EOF" >> $GITHUB_OUTPUT
+          set +e # temporarily disable 'exit on error'
+          OUTPUT=$(dotnet csharpier check . 2>&1)
+          EXIT_CODE=$?
+          set -e # re-enable 'exit on error'
 
-        # if check failed, explicitly exit with failure
-        if [ $EXIT_CODE -ne 0 ]; then
-          exit 1
-        fi
-      continue-on-error: true
+          echo "output<<EOF" >> $GITHUB_OUTPUT
+          echo "$OUTPUT" >> $GITHUB_OUTPUT
+          echo "EOF" >> $GITHUB_OUTPUT
+
+          # if check failed, explicitly exit with failure
+          if [ $EXIT_CODE -ne 0 ]; then
+            exit 1
+          fi
+        continue-on-error: true
 
   frontend:
     needs: changes
-    if: | 
+    if: |
       needs.changes.outputs.frontend_override == 'force' || (
         needs.changes.outputs.frontend_override != 'skip' &&
         needs.changes.outputs.frontend == 'true' || needs.changes.result != 'success'
@@ -126,55 +126,55 @@ jobs:
       format_output: ${{ steps.frontend_format_check.outputs.output }}
       outcome: ${{ steps.frontend_format_check.outcome }}
     steps:
-    - uses: actions/checkout@v4
+      - uses: actions/checkout@v4
 
-    # --- Set up Node.js ---
-    - name: Setup Node.js
-      uses: actions/setup-node@v3
-      with:
-        node-version: 24.10.0
+      # --- Set up Node.js ---
+      - name: Setup Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: 24.10.0
 
-    - name: Cache node modules for next.js
-      uses: actions/cache@v4
-      with:
-        # via https://nextjs.org/docs/pages/guides/ci-build-caching
-        path: ${{ github.workspace }}/Project.App/Project.Client/.next/cache
-        key: ${{ runner.os }}-nextjs-build-${{ hashFiles('Project.App/Project.Client/package-lock.json') }}-${{ hashFiles('Project.App/Project.Client/**/*.js', 'Project.App/Project.Client/**/*.jsx', 'Project.App/Project.Client/**/*.ts', 'Project.App/Project.Client/**/*.tsx') }}
-        restore-keys: |
-          ${{ runner.os }}-nextjs-build-${{ hashFiles('Project.App/Project.Client/package-lock.json') }}-
-          ${{ runner.os }}-nextjs-build-
+      - name: Cache node modules for next.js
+        uses: actions/cache@v4
+        with:
+          # via https://nextjs.org/docs/pages/guides/ci-build-caching
+          path: ${{ github.workspace }}/Project.App/Project.Client/.next/cache
+          key: ${{ runner.os }}-nextjs-build-${{ hashFiles('Project.App/Project.Client/package-lock.json') }}-${{ hashFiles('Project.App/Project.Client/**/*.js', 'Project.App/Project.Client/**/*.jsx', 'Project.App/Project.Client/**/*.ts', 'Project.App/Project.Client/**/*.tsx') }}
+          restore-keys: |
+            ${{ runner.os }}-nextjs-build-${{ hashFiles('Project.App/Project.Client/package-lock.json') }}-
+            ${{ runner.os }}-nextjs-build-
 
-    # --- Build Frontend ---
-    - name: Install frontend dependencies
-      working-directory: ./Project.App/Project.Client
-      run: npm install
+      # --- Build Frontend ---
+      - name: Install frontend dependencies
+        working-directory: ./Project.App/Project.Client
+        run: npm install
 
-    - name: Build frontend
-      working-directory: ./Project.App/Project.Client
-      run: npm run build
-    
-    - name: Lint frontend
-      working-directory: ./Project.App/Project.Client
-      run: npm run lint
-    
-    - name: Check frontend formatting
-      id: frontend_format_check
-      working-directory: ./Project.App/Project.Client
-      run: |
-        set +e # temporarily disable 'exit on error'
-        OUTPUT=$(npm run format:check -- --no-color 2>&1)
-        EXIT_CODE=$?
-        set -e # re-enable 'exit on error'
+      - name: Build frontend
+        working-directory: ./Project.App/Project.Client
+        run: npm run build
 
-        echo "output<<EOF" >> $GITHUB_OUTPUT
-        echo "$OUTPUT" >> $GITHUB_OUTPUT
-        echo "EOF" >> $GITHUB_OUTPUT
+      - name: Lint frontend
+        working-directory: ./Project.App/Project.Client
+        run: npm run lint
 
-        # if check failed, explicitly exit with failure
-        if [ $EXIT_CODE -ne 0 ]; then
-          exit 1
-        fi
-      continue-on-error: true
+      - name: Check frontend formatting
+        id: frontend_format_check
+        working-directory: ./Project.App/Project.Client
+        run: |
+          set +e # temporarily disable 'exit on error'
+          OUTPUT=$(npm run format:check -- --no-color 2>&1)
+          EXIT_CODE=$?
+          set -e # re-enable 'exit on error'
+
+          echo "output<<EOF" >> $GITHUB_OUTPUT
+          echo "$OUTPUT" >> $GITHUB_OUTPUT
+          echo "EOF" >> $GITHUB_OUTPUT
+
+          # if check failed, explicitly exit with failure
+          if [ $EXIT_CODE -ne 0 ]; then
+            exit 1
+          fi
+        continue-on-error: true
 
   add-formatting-warning-pr-comment:
     needs: [backend, frontend]
@@ -186,7 +186,7 @@ jobs:
       pull-requests: write
     steps:
       - uses: actions/checkout@v4
-      
+
       # --- Complain if formatting checks fail ---
       - name: Add PR comment if formatting checks fail
         env:
@@ -235,7 +235,7 @@ jobs:
         run: |
           PR_NUMBER=${{ github.event.pull_request.number }}
           COMMENT_BODY="### WARNING: CI Checks Skipped!\n\nThe following checks were manually skipped via commit message:\n"
-          
+
           if [ "${{ needs.changes.outputs.backend_override }}" == "skip" ]; then
             COMMENT_BODY+="- **Backend CI**\n"
           fi
